[package]
name = "patcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
androscalpel = { git = "ssh://git@git.mineau.eu/histausse/androscalpel.git", version = "0.1.0" }
